name: LouisGaltie
favicon: null
layout_spectrum: 0.6404829693492502
typography_spectrum: 0.6119728782214224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.688014873303473
  lightness: 0.05931672593578696
  saturation: 0.980160428211093
  rhythmicContrast: 0.26669412734918296
purpose: []
