name: LouisGaltie
favicon: null
layout_spectrum: 0.6404829693492502
typography_spectrum: 0.6119728782214224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#489ed0'
    - '#008ccd'
    - '#00527d'
    - '#182829'
    - '#8db3bc'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
